name: generacion

on:
  push:
    branches:
      - main

jobs:
  generar-codigo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17 (Temurin)
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate server code
        run: |
          java -jar openapi-generator-cli.jar generate -i Usuarios.yaml -g python-flask -o ./openapi_server

      - name: Zip generated code
        run: |
          zip -r openapi_server.zip openapi_server

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: openapi_server
          path: openapi_server.zip